### ISSUE TITLE
bug: ion-select cannot handle long lists with a visible scrollbar for web users (alert view, Ionic 4.4.2)

### ISSUE THREAD

**Issue by thmclellan** [ionic-team/ionic-framework#18487]
With Ionic 4.4.2, the ion-select component (with default alert interface) cannot be configured or styled to show a scrollbar for larger lists of more than 8 or so items. This makes the component unusable on larger lists where web-based users need scrollbars.  

For lists of 10 to 20 items, there are temporary workarounds for changing the alert-wrapper max-height and adjusting the inner alert button height, but for larger 20+ lists, there doesn't seem to be any way to force a scrollbar on the inner content section of the alert (e.g. `overflow-y: scroll` on the alert-wrapper class). 

After a lot of troubleshooting, it was easier to switch over to a plain select component for the larger. If this can't be easily fixed, then to support future CSS styling, it would be useful if there were an inner div inside of alert-wrapper, and if alert-wrapper could be set to overflow-y:scroll. There is something preventing `overflow-y:scroll !important`  from taking effect on alert-wrapper, even in Chrome dev tools... maybe someone with more flex experience has a solution.

**Comment by klemensz** [comment]
We have the same issue and we are targeting desktop browsers as well, so users there think there are no more options available in the list, although there are, but they cannot scroll... (the could with two fingers on the touchscreen, or if they have a mouse wheel, but they simply don't hit on it).

@thmclellan By "plain select component" you mean a simple HTML `<select>`?

**Comment by thmclellan** [comment]
Yes, in our case we found a regular HTML select (with some modern styling) was an easier solution for all platforms.

**Comment by klemensz** [comment]
We are now using this workaround (in global.scss):

```scss
/*
 * This adds a scroll bar to ionic alerts
 */
.alert-radio-group::-webkit-scrollbar, .alert-checkbox-group::-webkit-scrollbar {
    width: 0.7em;
    display: block !important;
}

.alert-radio-group::-webkit-scrollbar-track, .alert-checkbox-group::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
    box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}

.alert-radio-group::-webkit-scrollbar-thumb, .alert-checkbox-group::-webkit-scrollbar-thumb {
    background-color: darkgrey;
    outline: 1px solid slategrey;
}
```
