### ISSUE TITLE
feat: Possibility to adjust height of ticks, in ion-range

### ISSUE THREAD

**Issue by leonardofmed** [ionic-team/ionic-framework#20426]
# Feature Request

**Ionic version:**
[x] **4.x**

**Describe the Feature Request**
I can't adjust the tick height of ion-range element. Based on what I read on the Ionic forum and in Stackoverflow, only the ionic team can insert a variable that will make this change possible. 

**Describe Preferred Solution**
Add a variable to be able to change the height of ion-range ticks.

**Describe Alternatives**
Apply some selectable defaults?

**Related Code**
This is the class I want to modify:
```css
.range-tick {
    position: absolute;
    top: calc((var(--height) - var(--bar-height)) / 2); /* I want to modify this attribute */
    width: var(--bar-height);
    height: var(--bar-height); /* I want to modify this attribute */
    background: var(--bar-background-active);
    z-index: 1;
    pointer-events: none;
}
```
This class can be found in: `project_folder/node_modules/@ionic/core/dist/collection/components/range/`

**Additional Context**
Information of what I tried so far can be seen [here ](https://stackoverflow.com/questions/60096134/changing-ticks-height-in-ion-range) and [here](https://forum.ionicframework.com/t/changing-ticks-height-in-ion-range/182840).

**Comment by liamdebeasi** [comment]
Thanks for the issue. You can now customize the tick marks using the `tick` CSS Shadow Part:

```css
ion-range::part(tick) {
  height: 20px;
  top: 12px;
}
```

See https://ionicframework.com/docs/api/range#styling-with-css-shadow-parts for more information. I am going to close this as the requested functionality is now available in Ionic.
