### ISSUE TITLE
bug: --button-color does not modify cancel button color in toasts

### ISSUE THREAD

**Issue by somq** [ionic-team/ionic-framework#21818]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

Toast [custom css property](https://ionicframework.com/docs/api/toast#css-custom-properties) `--button-color` does not affect cancel button.

**Expected behavior:**

Affecting a color through `--button-color` should modify the color of all buttons present in the toast

**Steps to reproduce:**

1. start a template
2. add a toast
3. add a `--button-color` in app.scss

**Related code:**

```ts
    const toast = await this.toastCtrl.create({
      header: 'Toast header',
      message: 'Click to Close',
      position: 'top',
      buttons: [
        {
          side: 'start',
          icon: 'star',
          text: 'Favorite',
          handler: () => {
            console.log('Favorite clicked');
          }
        }, {
          text: 'Done',
          role: 'cancel',
          handler: () => {
            console.log('Cancel clicked');
          }
        }
      ]
    });
    toast.present();
```

```scss
ion-toast {
  --background: red;
  --button-color: red;
}
```

**Comment by piercers** [comment]
@maxfloden It's hacky, but this works:
```css
ion-toast {
    --button-color: var(--ion-color-primary);
    --ion-color-step-100: var(--ion-color-primary);
}
```

This leverages the CSS variable Ionic is using underneath:
```css
.toast-button-cancel {
    color: var(--ion-color-step-100, #e6e6e6);
}
```
