### ISSUE TITLE
feat: Add option to remove the shadow of the header.

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#22127]
# Feature Request

**Ionic version:**
`@ionic/angular: '5.3.2'`

**Describe the Feature Request**
Add an option / attribute to the ion-header / ion-toolbar to remove the shadow for a full flat header which can be combined with the page content (not line / shadow).

**Describe Preferred Solution**
`<ion-header no-shadow></ion-header>` or `<ion-header flat></ion-header>`

**Describe Alternatives**
My current solution is to hack the Ionic styles:

```scss
.header-md::after {
  /* Removes the toolbar shadow. */
  background: none;
}
```
Because the shadow is a background image.

**Related Code**

**html**
```html
<ion-app>
  <ion-header [class.hotfix]="hotfix">
    <ion-toolbar color="primary">
      <ion-title> About </ion-title>
    </ion-toolbar>
  </ion-header>

  <ion-content>
    <div class="about-header">
      <span>My Logo</span>
    </div>

    <ion-list>
      <ion-item>
        <ion-label>Enable Workaround</ion-label>
        <ion-toggle [(ngModel)]="hotfix"></ion-toggle>
      </ion-item>
    </ion-list>
  </ion-content>
</ion-app>

```

**scss**
```scss
.about-header {
  /* Same color like the header toolbar color. */
  background-color: #3880ff;
  color: white;
  padding: 16px;
  width: 100%;
  min-height: 150px;
  text-align: center;
  display: flex;
  justify-content: center;
  align-items: center;
}

.hotfix.header-md::after {
  /* Removes the toolbar shadow. */
  background: none;
}
```

### [StackBlitz Example](https://stackblitz.com/edit/ionic-angular-v5-header-shadow?file=src/app/app.component.html)

![demo](https://user-images.githubusercontent.com/60390085/93776731-28197280-fc24-11ea-9c1f-72cb12bd89cf.gif)

**Additional Context**

https://ionicframework.com/docs/api/header
https://ionicframework.com/docs/api/toolbar
