### ISSUE TITLE
feat: Support custom font styles in toast message. 

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#22803]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**
At this moment you cannot completely change the font-size, etc. for the toast. Beacuase of fixed shadow styles like like:

- padding
- line-height (20px)
- ...

https://ionicframework.com/docs/api/toast#css-custom-properties

**Describe Preferred Solution**
Add CSS variables to the custom variables of `ion-toast` to allow different font-sizes.

**Describe Alternatives**
There is no alternative. It's blocked by the shadow dom. We need these CSS variables.
Ok, I can already change the font-size. But deeper shadow styles like `line-height: 20px` in `.toast-message` ruins it.

**Related Code**

```scss
ion-toast.my-toast {
  --background: var(--ion-color-danger);
  --color: var(--ion-color-danger-contrast);
  --width: 50%;
  font-size: 3em;
  font-weight: bold;
  text-align: center;
  // Cannot access the line-height. :´(
}
```

**Additional Context**

![image](https://user-images.githubusercontent.com/60390085/105338465-e1d91d80-5bdb-11eb-80e8-4ca20e848ed5.png)

![image](https://user-images.githubusercontent.com/60390085/105339825-69735c00-5bdd-11eb-8878-835e9473a46f.png)
![image](https://user-images.githubusercontent.com/60390085/105339936-87d95780-5bdd-11eb-9b78-3d8c57222e2b.png)

### [StackBlitz Demo](https://stackblitz.com/edit/ionic-5-toast-font-style-issue?embed=1&file=src/app/tab1/tab1.page.ts)

Feel free to turn this problem into a bug.

**Comment by liamdebeasi** [comment]
Thanks for the feature request. I am going to close this as this is already possible in Ionic Framework. You can target the `message` part to customize the text:

```css
ion-toast.my-toast::part(message) {
  line-height: 40px;
}
```

See https://ionicframework.com/docs/api/toast#css-shadow-parts for more information.
