### ISSUE TITLE
bug: some ion-button border options are not getting applied 

### ISSUE THREAD

**Issue by Deitsch** [ionic-team/ionic-framework#23243]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

`--border-color`, `--border-width` and `--border-style` are not getting applied to the button. `--border-radius` works as expected thus it should work for the others as well.
Here is an image of the button i want to apply the border styles
<img width="111" alt="Bildschirmfoto 2021-04-27 um 11 53 58" src="https://user-images.githubusercontent.com/44440587/116223154-8cb72580-a74f-11eb-9ee1-8128a739a905.png">

**Expected behavior:**
All border settings are applied to the button like `--border-radius.

**Steps to reproduce:**
Create a button and apply border CSS Custom Properties described on https://ionicframework.com/docs/api/button.
```html
<ion-button i18n type="button" color="primary">Log in</ion-button>
```
```css
ion-button {
  --border-radius: 100px; //var(--ion-border-secondary-radius);
  --border-width: 1; //var(--ion-border-secondary-width);
  --border-color: black; //var(--ion-border-secondary-color);
  --border-style: solid; //var(--ion-border-secondary-style);
}
```

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```

Ionic:

   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v15.4.0 (/usr/local/Cellar/node/15.4.0/bin/node)
   npm    : 7.7.6
   OS     : macOS Big Sur


```
