### ISSUE TITLE
bug: --background-hover being overridden on ion-button fill="clear" and color

### ISSUE THREAD

**Issue by reed-lawrence** [ionic-team/ionic-framework#23441]
**Ionic version:**
"@ionic/core": "^5.6.9"
"@ionic/angular": "^5.6.9"
 "@angular/core": "~10.0.0"

**Current behavior:**
`<ion-button fill="clear" style="--background-hover: transparent; --background-hover-opacity: 0;"> `

Hovered ion-buttons still show a background. 

![Screen Shot 2021-06-10 at 8 55 21 AM](https://user-images.githubusercontent.com/30061591/121537632-b2c81a80-c9c9-11eb-8ef1-478e6b85e2d7.png)

Chrome inspector shows:
![Screen Shot 2021-06-10 at 8 43 45 AM](https://user-images.githubusercontent.com/30061591/121535672-fb7ed400-c9c7-11eb-873a-ccb7925dcd34.png)

Which digging through the node_modules:
node_modules/@ionic/core/dist/collection/components/button/button.md.css

Line 417:
```scss
@media (any-hover: hover) {
  :host(.button-solid.ion-color:hover) .button-native::after {
    background: var(--ion-color-contrast);
    opacity: 0.08;
  }

  :host(.button-clear.ion-color:hover) .button-native::after,
:host(.button-outline.ion-color:hover) .button-native::after {
    background: var(--ion-color-base);
    opacity: 0.04;
  }
}
```

Which looks to be a compiled output from here: https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/button/button.md.scss

**Expected behavior:**
On a desktop application (untested on mobile):

<ion-button fill="clear" style="--background-hover: transparent; --background-hover-opacity: 0;"> 

The above styles would expect the button to not have a background when hovered.
