### ISSUE TITLE
bug: Popover does not properly respond to media query

### ISSUE THREAD

**Issue by PhilippeKayser** [ionic-team/ionic-framework#23449]
# Bug Report

I am working on a web-app, that if opened in a desktop browser, reduces the ion-app containers width. One of the requirements is to retain a mobile appearance on every platform. In order to achieve this I use a media query, which resizes the ion-app depending on the width of the screen to a maximum of 700px and positions the ion-app container to the center of the window using margin, width and transform.

In some situations I want the user to open a *help* dialogue and to achieve this I am using the **ion-popover** component, which I create with the **PopoverController**. Unfortunately this Popover is not properly displayed in the center of the newly positioned ion-app container. It does not properly take into account the transform property of the css. If I omit the transform property, it correctly displays in the center of the screen, but then the ion-app container is not correctly positioned.

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

The popover element is not displayed in the center of the ion-app container.

**Expected behavior:**

The popover should be displayed in the center of the ion-app container, unrelated to it's modified width and position.

**Steps to reproduce:**

- Clone repo
- `npm install`
- `ionic serve`
- Make sure your window is wider than 700px
- Click Button **Click Me**

**Related code:**
[GitHub Repository](https://github.com/PhilippeKayser/ionic-media-query-popover-bug)

Media Query to reduce the width of the ion-app.
``` css
@media screen and (min-width: 700px){   
    ion-app {
        margin-left: 50%;
        width: 700px;
        border-left: 1px solid var(--ion-color-medium-shade);
        border-right: 1px solid var(--ion-color-medium-shade);
        transform: translateX(-50%);
    }
}
```

Method opening the Popover. The html contains the `$event` argument.
```javascript
async openPopover(event) {
    const popover = await this._popoverController.create({
        component: PopoverContentComponent,
    });
    popover.present();
}
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.16.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.9
   @angular-devkit/build-angular : 12.0.4
   @angular-devkit/schematics    : 12.0.4
   @angular/cli                  : 12.0.4
   @ionic/angular-toolkit        : 4.0.0

Utility:

   cordova-res                          : 0.15.3
   native-run (update available: 1.4.0) : 1.3.0

System:

   NodeJS : v14.16.0 (/usr/local/bin/node)
   npm    : 7.13.0
   OS     : macOS Big Sur
```
