### ISSUE TITLE
bug/feat: ion-select with more than 5 items lacks visual indicator on Material Theme

### ISSUE THREAD

**Issue by cmaas** [ionic-team/ionic-framework#23760]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

An `ion-select` with more than 5 items has no visual indicator that the selection area is scrollable, but only for the Material Theme. The iOS theme shows half of the 6th item, which serves as a visual indicator that the whole area is scrollable.

The reason for this is simple:
```css
.alert-radio-group.sc-ion-alert-ios, .alert-checkbox-group.sc-ion-alert-ios {
  max-height: 240px;
}
.alert-tappable.sc-ion-alert-ios {
    height: 44px;
}
```
240px / 44px = 5,45 items to show.

```css
.alert-radio-group.sc-ion-alert-md, .alert-checkbox-group.sc-ion-alert-md {
    max-height: 240px;
}

.alert-tappable.sc-ion-alert-md {
    height: 48px;
}
```
240px / 48px = exactly 5 items.

Solution:
```css
.alert-radio-group.sc-ion-alert-md, .alert-checkbox-group.sc-ion-alert-md {
    max-height: 264px;
}
```
Because 264px / 48px = 5.5 items.

Sure, I can override this in `app.css`, but I think it makes sense as a good default for all ionic apps, since it is confusing for users.

### Expected Behavior

Show 5.5 items in Material Theme

### Steps to Reproduce

```
<ion-item>
          <ion-label>Music</ion-label>
          <ion-select value="03">
            <ion-select-option value="01">Alice in Chains</ion-select-option>
            <ion-select-option value="02">Green Day</ion-select-option>
            <ion-select-option value="03">Nirvana</ion-select-option>
            <ion-select-option value="04">Pearl Jam</ion-select-option>
            <ion-select-option value="05">Smashing Pumpkins</ion-select-option>
            <ion-select-option value="06">Soundgarden</ion-select-option>
            <ion-select-option value="07">Stone Temple Pilots</ion-select-option>
          </ion-select>
 </ion-item>
```

Or see here and toggle between themes: https://ionicframework.com/docs/api/select

### Code Reproduction URL

https://ionicframework.com/docs/api/select

### Ionic Info

Package.json:

"@ionic/core": "5.6.12"

### Additional Information

<img width="300" alt="list-ios" src="https://user-images.githubusercontent.com/6094364/129008362-81d6c9a7-9af9-4a44-9be6-7a2d6015e96c.png">
<img width="309" alt="list-md" src="https://user-images.githubusercontent.com/6094364/129008366-3db2b32d-310f-454b-8927-083b7db5a88a.png">
