### ISSUE TITLE
bug: why are background images used as borders instead of shadows or border properties?

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#23868]
### Prequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [ ] v6.x

### Description

It's more of a question than a bug. But nothing for the forum or other platforms. I was just wondering. Because an image cannot simply be adapted with a theme (e.g. dark mode).

For example the `ion-header` and `ion-footer` has in its pseudo selctors an background-image for the shadow / border.

```css
.footer-md::before {
  /* ... */
  background-image: url("data:image/png;base64,blabla");
}
```

I expected `border` or `box-shadow` with CSS variable.

For example:

```css
.header-md::after {
  background-image: none;
  position: absolute;
  left: 0;
  right: 0;
  bottom: -1px;
  border-bottom: thin solid
    var(--ion-item-border-color, var(--ion-border-color, var(--ion-color-step-150, rgba(0, 0, 0, 0.13))));
}
```
Btw. this is my workaround for a thin border (more modern look) which also respects my theme. The border-bottom color value is the same as a item border has. 

You can use this code if you want. Same with the footer, just on `::before`.
