### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by farisfaisalthena** [ionic-team/ionic-framework#24447]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

When trying to style iOS `ion-modal` on `variables.scss`, the modal background color does not change

### Expected Behavior

When using `--ion-background-color` on `ion-modal` styling, the background should be changes to our desired color instead its following the main `--ion-background-color`

### Steps to Reproduce

1. Create a new ionic angular app
2. Paste the following code and replace everything inside `variables.scss`

```css
@mixin light-theme {
  /** success **/
  --ion-color-success: #2dd36f;
  --ion-color-success-rgb: 45, 211, 111;
  --ion-color-success-contrast: #ffffff;
  --ion-color-success-contrast-rgb: 255, 255, 255;
  --ion-color-success-shade: #28ba62;
  --ion-color-success-tint: #42d77d;

  /** warning **/
  --ion-color-warning: #ffc409;
  --ion-color-warning-rgb: 255, 196, 9;
  --ion-color-warning-contrast: #000000;
  --ion-color-warning-contrast-rgb: 0, 0, 0;
  --ion-color-warning-shade: #e0ac08;
  --ion-color-warning-tint: #ffca22;

  /** danger **/
  --ion-color-danger: #eb445a;
  --ion-color-danger-rgb: 235, 68, 90;
  --ion-color-danger-contrast: #ffffff;
  --ion-color-danger-contrast-rgb: 255, 255, 255;
  --ion-color-danger-shade: #cf3c4f;
  --ion-color-danger-tint: #ed576b;

  /** dark **/
  --ion-color-dark: #222428;
  --ion-color-dark-rgb: 34, 36, 40;
  --ion-color-dark-contrast: #ffffff;
  --ion-color-dark-contrast-rgb: 255, 255, 255;
  --ion-color-dark-shade: #1e2023;
  --ion-color-dark-tint: #383a3e;

  /** medium **/
  --ion-color-medium: #92949c;
  --ion-color-medium-rgb: 146, 148, 156;
  --ion-color-medium-contrast: #ffffff;
  --ion-color-medium-contrast-rgb: 255, 255, 255;
  --ion-color-medium-shade: #808289;
  --ion-color-medium-tint: #9d9fa6;

  /** light **/
  --ion-color-light: #f4f5f8;
  --ion-color-light-rgb: 244, 245, 248;
  --ion-color-light-contrast: #000000;
  --ion-color-light-contrast-rgb: 0, 0, 0;
  --ion-color-light-shade: #d7d8da;
  --ion-color-light-tint: #f5f6f9;
}

@mixin dark-theme {
  --ion-color-success: #2fdf75;
  --ion-color-success-rgb: 47, 223, 117;
  --ion-color-success-contrast: #000000;
  --ion-color-success-contrast-rgb: 0, 0, 0;
  --ion-color-success-shade: #29c467;
  --ion-color-success-tint: #44e283;

  --ion-color-warning: #ffd534;
  --ion-color-warning-rgb: 255, 213, 52;
  --ion-color-warning-contrast: #000000;
  --ion-color-warning-contrast-rgb: 0, 0, 0;
  --ion-color-warning-shade: #e0bb2e;
  --ion-color-warning-tint: #ffd948;

  --ion-color-danger: #ff4961;
  --ion-color-danger-rgb: 255, 73, 97;
  --ion-color-danger-contrast: #ffffff;
  --ion-color-danger-contrast-rgb: 255, 255, 255;
  --ion-color-danger-shade: #e04055;
  --ion-color-danger-tint: #ff5b71;

  --ion-color-dark: #f4f5f8;
  --ion-color-dark-rgb: 244, 245, 248;
  --ion-color-dark-contrast: #000000;
  --ion-color-dark-contrast-rgb: 0, 0, 0;
  --ion-color-dark-shade: #d7d8da;
  --ion-color-dark-tint: #f5f6f9;

  --ion-color-medium: #989aa2;
  --ion-color-medium-rgb: 152, 154, 162;
  --ion-color-medium-contrast: #000000;
  --ion-color-medium-contrast-rgb: 0, 0, 0;
  --ion-color-medium-shade: #86888f;
  --ion-color-medium-tint: #a2a4ab;

  --ion-color-light: #222428;
  --ion-color-light-rgb: 34, 36, 40;
  --ion-color-light-contrast: #ffffff;
  --ion-color-light-contrast-rgb: 255, 255, 255;
  --ion-color-light-shade: #1e2023;
  --ion-color-light-tint: #383a3e;

  .ios {
    --ion-background-color: red;
    --ion-background-color-rgb: 0, 0, 0;

    --ion-text-color: #ffffff;
    --ion-text-color-rgb: 255, 255, 255;

    --ion-color-step-50: #0d0d0d;
    --ion-color-step-100: #1a1a1a;
    --ion-color-step-150: #262626;
    --ion-color-step-200: #333333;
    --ion-color-step-250: #404040;
    --ion-color-step-300: #4d4d4d;
    --ion-color-step-350: #595959;
    --ion-color-step-400: #666666;
    --ion-color-step-450: #737373;
    --ion-color-step-500: #808080;
    --ion-color-step-550: #8c8c8c;
    --ion-color-step-600: #999999;
    --ion-color-step-650: #a6a6a6;
    --ion-color-step-700: #b3b3b3;
    --ion-color-step-750: #bfbfbf;
    --ion-color-step-800: #cccccc;
    --ion-color-step-850: #d9d9d9;
    --ion-color-step-900: #e6e6e6;
    --ion-color-step-950: #f2f2f2;

    --ion-item-background: #000000;

    --ion-card-background: #1c1c1d;

    ion-modal {
      --ion-background-color: var(--ion-color-step-100);
      --ion-toolbar-background: var(--ion-color-step-150);
      --ion-toolbar-border-color: var(--ion-color-step-250);
    }
  }

  .md {
    --ion-background-color: #121212;
    --ion-background-color-rgb: 18, 18, 18;

    --ion-text-color: #ffffff;
    --ion-text-color-rgb: 255, 255, 255;

    --ion-border-color: #222222;

    --ion-color-step-50: #1e1e1e;
    --ion-color-step-100: #2a2a2a;
    --ion-color-step-150: #363636;
    --ion-color-step-200: #414141;
    --ion-color-step-250: #4d4d4d;
    --ion-color-step-300: #595959;
    --ion-color-step-350: #656565;
    --ion-color-step-400: #717171;
    --ion-color-step-450: #7d7d7d;
    --ion-color-step-500: #898989;
    --ion-color-step-550: #949494;
    --ion-color-step-600: #a0a0a0;
    --ion-color-step-650: #acacac;
    --ion-color-step-700: #b8b8b8;
    --ion-color-step-750: #c4c4c4;
    --ion-color-step-800: #d0d0d0;
    --ion-color-step-850: #dbdbdb;
    --ion-color-step-900: #e7e7e7;
    --ion-color-step-950: #f3f3f3;

    --ion-item-background: #1e1e1e;

    --ion-toolbar-background: #1f1f1f;

    --ion-tab-bar-background: #1f1f1f;

    --ion-card-background: #1e1e1e;
  }
}

:root {
  @include light-theme;
}

@media (prefers-color-scheme: no-preferences), (prefers-color-scheme: light) {
  :root {
    @include light-theme;
  }
}

@media (prefers-color-scheme: dark) {
  :root {
    @include dark-theme;
  }
}
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.1.2
   @angular-devkit/schematics    : 13.1.2
   @angular/cli                  : 13.1.2
   @ionic/angular-toolkit        : 5.0.3

Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : not installed
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.5.0

System:

   NodeJS : v16.13.1 (/usr/local/bin/node)
   npm    : 8.1.2
   OS     : macOS Monterey

**Comment by sean-perkins** [comment]
@farisfaisalthena are you referencing the docs for the available CSS variables for `ion-modal`?

https://ionicframework.com/docs/api/modal#css-custom-properties

`--background` is the appropriate CSS variable for styling the background of the modal content.

`--ion-background-color` is used for the `body` container's background color and a few other fallbacks/defaults.

**Comment by farisfaisalthena** [comment]
I just copy and pasted from the starter file which did not use --background

**Comment by sean-perkins** [comment]
@farisfaisalthena it does appear that the starters ship with some defaults, we could likely better document those in the starters if it's a repeat problem. 

I'm going to close this issue, as the components do have variables that can be targeted to theme the modals. 

If the example you are working with includes [`ion-content`](https://ionicframework.com/docs/api/content#css-custom-properties) or [`ion-item`](https://ionicframework.com/docs/api/item#css-custom-properties), you may want to additionally refer to their CSS variables; as they also have a background color applied to their elements (through `--background`).

**Comment by farisfaisalthena** [comment]
I tried with `--background` and its still not working. I want to set a default color for all modals on iOS mode. Below is the updated code

```css
.ios {
 // Other Stylings

ion-modal {
      --background: red;
    }
}
```

**Comment by sean-perkins** [comment]
@farisfaisalthena it looks like I misspoke, `--ion-background-color` does get applied to `ion-content`, so you will not need to additionally target those styles.

With these styles at the root of the `variables.scss`:
```css
.ios ion-modal {
  --ion-background-color: red;
}
```

The background color of the modal changes to red:
<img width="287" src="https://user-images.githubusercontent.com/13732623/146873039-b6b31c75-7257-4e12-87c3-43f261352299.png">

**Comment by farisfaisalthena** [comment]
yeah thats the issue because when changing the background it does not apply the color. It follows the main background color. I have updated the code on the original issue which is `.ios ion-modal`

**Comment by sean-perkins** [comment]
@farisfaisalthena I'm having a hard time following what issue you are experiencing. Would you mind creating a reproduction app without any custom modifications? The mixins in your example do not appear to come with the starter. 

It looks like the mixin is doing this:
```css
@media (prefers-color-scheme: dark) {
  :root {
   --var: value;
  }

  :root body {
   --var: value;
  }

  :root .ios ion-modal {
   --var value;
  }
}
```

instead of what the starter ships with:
```css
@media (prefers-color-scheme: dark) {
  :root {
    --var: value;
  }

  body {
    --var: value;
  }

  .ios ion-modal {
    --var: value;
  }
}
```

If this is an issue with your custom mixin, I would encourage you to post the issue on the forums.
