### ISSUE TITLE
bug: Focusing overflowing content scrolls the wrong viewport

### ISSUE THREAD

**Issue by Julien-Marcou** [ionic-team/ionic-framework#24499]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [X] v5.x
- [X] v6.x

### Current Behavior

On chromium browsers, focusing an element that is partially visible will makes the browser to attempt to scroll so that the focused element is fully visible on the screen (to my knowledge, this is a feature that only exists on chromium browsers).

But because the `.inner-scroll` part of the `<ion-content>` component is bigger than the <ion-content> itself due to negative positioning and additional padding:

```css
.inner-scroll {
  top: calc(var(--offset-top) * -1);
  bottom: calc(var(--offset-bottom) * -1);
  padding-top: calc(var(--padding-top) + var(--offset-top));
  padding-bottom: calc(var(--padding-bottom) + var(--keyboard-offset) + var(--offset-bottom));
}
```

This makes the browser thinks that content that are partially visible (relative to the `<ion-content>`) are alreay visible within the `.inner-scroll`, therefore, the browser will attempt to scroll other element of the interface to make the element fully visible instead of scrolling the `.inner-scroll` (and yes, the browser is able to scroll element that are not even scrollable, i.e: `overflow: hidden`).

In my case, the browser is scrolling the closest `.ion-page` parent of the `<ion-content>`, this makes the entire app move up, making the `<ion-header>` no longer accessible and creating empty space below the `<ion-content>`.

You can see this by executing this command in the browser's console:

```js
document.querySelector('ion-content').closest('.ion-page').scrollTop;
// Should outputs 0, but outputs 56 after the browser has made the focused element fully visible
```

This outputs the exact same value as the negative positioning, in my case, the `.ion-page` (which is not even scrollable) has been scrolled by 56px.

### Expected Behavior

The browser should not scroll the parent `.ion-page` and should scroll the `.inner-scroll` instead.

The only solution I see to this, is not to make the `.inner-scroll` bounding box bigger than the one of the `<ion-content>`.
Is there a reason it has been made like this in the first place ?

You will see on the video I have uploaded, that I can fix this by applying the `padding` value to the `margin` instead.
In my case:

```css
ion-content::part(scroll) {
  padding: 0;
  margin: 56px 0;
}
```

But this could also be solved with:

```css
ion-content::part(scroll) {
    top: 0;
    bottom: 0;
    padding: 0;
}
```

Which entirely remove the need of the negative positioning, but these solutions may have side effects that I'm not aware of.

### Steps to Reproduce

- Create an app with an <ion-content>
- Add several elements that are focusable inside of it, so that the <ion-content> become scrollable
- Make it so you have a focusable element partially visible on your screen (it works best if you have big element like in my video)
- Click the partilly visible element to focus it (it only works if you focus a non focused element, as the browser does not attempt to scroll to make it fully visible when it is already focused)

You'll see that the browser has scrolled the parent `.ion-page` instead of the `.inner-scroll`.

### Ionic Info

@ionic/cli : 6.18.1
@ionic/angular : 6.0.1
@angular-devkit/build-angular : 13.1.2
@angular-devkit/schematics : 13.1.2
@angular/cli : 13.1.2
@capacitor/core : 3.3.3
NodeJS : v16.13.1
npm : 8.3.0

### Additional Information

Here is a video demonstrating the issue on Chrome:

https://youtu.be/HaSpes69u-U

This video has been recorded using Ionic 6 on Chrome, but the bug can be reproduced on Android 12 with Ionic 5 and Ionic 6.

**Comment by Julien-Marcou** [comment]
I added the reproduction repository.

## Here's what you should see right after the app has booted:

![before-focus](https://user-images.githubusercontent.com/4369075/148702348-c448d5ee-8973-4e52-8b1d-04c3e2933d20.png)

## And here's what you should see after you have clicked on the 4th button:

![after-focus](https://user-images.githubusercontent.com/4369075/148702352-8c26f355-3d26-4292-933e-1ff71818cc17.png)

**Comment by Julien-Marcou** [comment]
up

@liamdebeasi just so this issue does not get lost with the "needs reproduction" tag while the reproduction has been added 😅

**Comment by liamdebeasi** [comment]
Whoops sorry, not sure how it asked you for a reproduction again 😂 . I will take a look at your reproduction and get back to you - thanks!

**Comment by liamdebeasi** [comment]
I can reproduce this behavior, but I am not sure what is causing this. I will assign a bug label for now and update this thread when I have more to share.

**Comment by Julien-Marcou** [comment]
Yes, sorry I forgot to mention that 😅

What I can tell you, is that replacing the negative positioning of the `.ion-scroll`  element

```css
.inner-scroll {
  top: calc(var(--offset-top) * -1);
  bottom: calc(var(--offset-bottom) * -1);
  padding-top: calc(var(--padding-top) + var(--offset-top));
  padding-bottom: calc(var(--padding-bottom) + var(--keyboard-offset) + var(--offset-bottom));
}
```

with:

```css
.inner-scroll {
  top: calc(var(--offset-top) * -1);
  bottom: calc(var(--offset-bottom) * -1);
  margin-top: calc(var(--padding-top) + var(--offset-top));
  margin-bottom: calc(var(--padding-bottom) + var(--keyboard-offset) + var(--offset-bottom));
}
```

or:

```css
.inner-scroll {
  top: 0;
  bottom: 0;
}
```

or even:

```css
ion-content {
  overflow: hidden;
}
```

fixes the problem.

The reason behind this, I believe, is that paddings are considered by Chrome as "content that should be presented to the user".

When you look at the DOM tree, you can see the `.ion-scroll` element is actually taller than the `<ion-content>` iteself. Resulting in content that is not "visible" to the user (even though in our case it doesn't matter, because there is actually nothing to see in the content that is behind the `<ion-toolbar>` & `<ion-tab-bar>`).

So, because the `<ion-content>` has overflowing content, it is considered as "scrollable" by the browser, even though it is not scrollable by the user (until you explicitly add the rule `ion-content { overflow: auto; }`, which we do not want as the `.ion-scroll` element is here for that).

Then when you click an element that is partially visible within a "scrollable" element, the browser will attempt to bring it into the "visible part of the viewport" so it is fully visible.

In our case the browser scrolls the `<ion-content>`, although it could scroll the `.ion-scroll` viewport to achieve the same result, the browser doesn't know it, it scrolls from the root of the document until the focused element is reached or the focused element is considered visible.

Which result in Chrome scrolling the `<ion-content>` instead of the `.ion-scroll` element.

At this point I don't see any other solutions than the ones I suggested above.
The reason I don't open a Pull Request, is because I don't understand this negative positioning, IMO we could totally remove the `padding-top` & `padding-bottom` rules, and replace the negative positioning with `top: 0` & `bottom: 0`, but may be there is reason behind it that I don't understand, may be for scrolling effect when you reach the bottom/top of the viewport, or the sticky `<ion-header>` that changes on iOS when you start scrolling ?

Hopefully this will help you understand the problem ^^

**Comment by Julien-Marcou** [comment]
Although this is a feature of Chromium browsers, I don't entirely agree on the `external` label ^^

IMO, the problem lies in a "bad layouting" from Ionic (between the `<ion-tabs>` & the `<ion-content>`), using negative values to make the `.inner-scroll` (`<ion-content>`'s viewport) bigger than the `.tabs-inner` (space allocated by the `<ion-tabs>` for its content)  itsn't good practice.

The `top` negative value is needed in order to make the translucent effect on iOS:
Because the `<ion-header>` is not part of the viewport, by "expanding" the viewport up with a negative value it makes it appear under the `<ion-header`> to simulate a `position: sticky;` on the `<ion-header>`. 

Altough this would require some breaking changes, it would definitely be cleaner to have the `<ion-header>` be part of the viewport and be sticky, instead of simulating this with negative values (also on desktop it would make the scrollbar fully visible, instead of hidding it behind the `<ion-header>`.

As for the `bottom` negative value, I have no clue why it's here, I don't see any translucent effect on the `<ion-tab-bar>` so it seems totally unnecessary (I might be wrong, but I haven't found anything yet).

---

For people who may have encountered this issue, only removing the `bottom` negative value is enought to fix this issue and it doesn't seem to add any side effect.

This is because even though Chromium browsers are able to scroll non-scrollable elements like the `.ion-page`, it still can't scroll to negative value, and because every element has by default a scroll position of 0, it can only go in one direction at the beginning.


Here is what I did to fix the problem:

```css
/* insider your global.scss */
ion-content::part(scroll),
ion-content::part(background) {
  bottom: 0;
  padding-bottom: 0;
}
```

**Comment by liamdebeasi** [comment]
> As for the bottom negative value, I have no clue why it's here, I don't see any translucent effect on the <ion-tab-bar> so it seems totally unnecessary (I might be wrong, but I haven't found anything yet). 

That is a known bug: https://github.com/ionic-team/ionic-framework/issues/17676

> Although this would require some breaking changes, it would definitely be cleaner to have the <ion-header> be part of the viewport and be sticky, instead of simulating this with negative values (also, on desktop, it would have the benefit to make the scrollbar fully visible, instead of hidding it behind the <ion-header>).

While this change likely would give us the same "fullscreen" effect, it would extend to Android devices and users who do not want the fullscreen effect, so I am not sure that would be a good change to make.

**Comment by Julien-Marcou** [comment]
> That is a known bug: #17676

Oh, ok, that make senses now 😅, so to do what I just said, it would also require to make the `<ion-tab-bar>` be part of the viewport.

> While this change likely would give us the same "fullscreen" effect, it would extend to Android devices and users who do not want the fullscreen effect, so I am not sure that would be a good change to make.

I'm not sure to understand, the "fullscreen" effect is already present on Android device at the moment, the viewport takes the entire screen's size, but the top & bottom parts of it are hidden behind the `<ion-header>` & the `<ion-tab-bar>`, making these 2 elements be part of the viewport and sticky would give the same result (as scrollbars are not visible on mobile devices anyway), am I wrong ?

(I agree this would need quite a lot of changes, which may not be conceivable at the moment)

**Comment by liamdebeasi** [comment]
The main issue is that the header/footer would become part of the scrollable content. While this would give us the desired fullscreen effect, the header/footer would now rubber band:

https://user-images.githubusercontent.com/2721089/174155078-4f57418f-3abd-4fc3-9cec-0ce70976bf48.MP4

The header/footer on mobile apps should stay fixed even when the content rubber band.

(CodePen source: https://codepen.io/liamdebeasi/pen/abqMYmJ)

**Comment by Julien-Marcou** [comment]
I didn't thought of the stretching rubber effect 🤦‍♂️ look's like this problem is getting more and more complicated 😅

Well, at least, as I don't need the translucent effect on the `<ion-tab-bar>`, removing the bottom negative margin is enought for me at the moment.

I'll try to make some search to see if this can be fixed by other means, so we don't lose any feature.

**Comment by Julien-Marcou** [comment]
I may have good news for you @liamdebeasi 😄

I was trying to fix #17676 so I could work on a fix for my bug, and fixing #17676 seems to fix both issues, I have update my original reproduction repo (https://github.com/Julien-Marcou/ionic-focus-scroll-bug), the fix is disabled on "Tab 1" but enabled on "Tab 2".

The idea is to extends the `.tabs-inner` of the `<ion-tabs>` by making the `<ion-tab-bar>` fixed at the bottom and making `.tabs-inner` take the entire screen's height.

Here the CSS I added:

```scss
// Tab bar height is hard coded, so add the value to a variable here to re-use it elsewhere
ion-app {
  &.md {
    --tab-bar-height: 56px;
  }
  &.ios {
    --tab-bar-height: 50px;
  }
}

// Fix ion-tabs translucent effect not working
ion-tabs {
  display: block;

  .tabs-inner {
    height: 100%;
    padding-bottom: var(--tab-bar-height);
  }

  ion-tab-bar {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
  }
}

ion-content {
  &::part(background) {
    bottom: 0;
  }
  &::part(scroll) {
    bottom: 0;
    padding-bottom: calc(var(--padding-bottom) + var(--keyboard-offset) + var(--tab-bar-height));
  }
}
```

This can definitely be made cleaner ^^
