### ISSUE TITLE
bug(ion-header): applying box-shadow leads to laggy back navigation animation

### ISSUE THREAD

**Issue by DwieDima** [ionic-team/ionic-framework#25110]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

if the `box-shadow` is added to `ion-header,` the back navigation is laggy. The same behavior applies when `box-shadow` is applied to `ion-toolbar.`

https://user-images.githubusercontent.com/26873275/163140132-36d76ba9-e1f3-423c-ab23-c7b311122670.mov

### Expected Behavior

there should be no lag if you navigate back using box-shadow.

### Steps to Reproduce

apply global styling for `ion-header` inside `global.scss`:

```scss

ion-header {
  box-shadow: 0 0 10px 0 rgba(var(--ion-color-dark-rgb), 0.4);
}
```

Now just navigate back and forward.

The current "workaround" is to use instead of `box-shadow`, the `filter` property:

```scss
ion-header {
  filter: drop-shadow(0 0 10px rgba(var(--ion-color-dark-rgb), 0.4));
}
```

Here i'm not sure about compatibility and performance issues, so i would prefer to use `box-shadow`.

### Ionic Info

Ionic:

   Ionic CLI : 5.4.16

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v16.14.2
   npm    : 8.5.0
   OS     : macOS Monterey

**Comment by liamdebeasi** [comment]
Did you make the repo public? I am getting a "Not Found" error.

**Comment by DwieDima** [comment]
> Did you make the repo public? I am getting a "Not Found" error.

Sorry, its now public

**Comment by liamdebeasi** [comment]
Thanks! I can reproduce the described behavior, but this is not a bug in Ionic.

The iOS page transition animates the elements inside of the toolbar, but not the toolbar or header elements themselves: https://github.com/ionic-team/ionic-framework/blob/main/core/src/utils/transition/ios.transition.ts#L527-L577

You need to apply the box shadow to `ion-header .header-background` instead for this to work as expected.

**Comment by DwieDima** [comment]
Ah good to know!
Thank you for sharing this 😄

**Comment by DwieDima** [comment]
i just tried your suggestion, but this wont display any box-shadow to the header:

```scss
ion-header .header-background {
  box-shadow: 0 0 10px 0 rgba(var(--ion-color-dark-rgb), 0.4) !important;
}
```

also i haven't found any class `header-background`.

![image](https://user-images.githubusercontent.com/26873275/163327024-11b075a7-f5ce-4b1b-9f7d-067aa77de3ba.png)
