### ISSUE TITLE
feat: Make v6 datetime time section style-able

### ISSUE THREAD

**Issue by pjc2007** [ionic-team/ionic-framework#25691]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Would just like to have the time part of the new datetime.

With the colors I use for dark theme, on iOS, the unselected numbers are not not really visible.
Even if I set mode='md', it changed the date style, but not the time picker.

![image](https://user-images.githubusercontent.com/10663978/181658130-1c28ef80-2d78-4587-9a76-c492d762fc81.png)

I could find no way to target and style either the background, or the numbers

### Describe the Use Case

Make numbers of datetime time picker more able to style on iOS (or any platform)

### Describe Preferred Solution

To be able to style the time picker part of the datetime v6

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide an example of how you are trying to style the picker? Understanding which pieces of the picker you are trying to style will help us expose the correct APIs.

**Comment by pjc2007** [comment]
So, in my case if I could style the following elements (highlighted).

![image](https://user-images.githubusercontent.com/10663978/182257465-b1fb9709-6e60-4fbc-9383-db767178bfa6.png)

Can see here that the unselected text is now visible

**Comment by liamdebeasi** [comment]
Thanks! The styling you want should be possible, though I do think our docs are lacking in guidance on how to do this.

Styling the time picker in datetime is a bit tricky because the time picker itself is rendered outside of `ion-datetime` so that it overlays the entire app. As a result, you need to target the `ion-popover` element which renders the wheel picker.

The relevant code looks something like this:

```css
ion-popover {
  /* The RGB value is needed so that we can use alpha channels (i.e. opacity) */
  --ion-background-color-rgb: 18,14,34;
  --ion-background-color: #120e22;

  /* This controls the active highlight on iOS. */
  --ion-color-step-150: var(--background);
  
  /* This controls the non-active text */
  color: white;
}
```

---- 

Here is a full example if you are interested: https://codepen.io/liamdebeasi/pen/zYWREZE
