### ISSUE TITLE
bug: Whitespace stripped from certain CSS selectors in ionic.bundle.css

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/ionic-framework#25766]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The minified stylesheet `ionic.bundle.css` has whitespace stripped in `:not` selectors. This leads to existing selectors such as:
```css
ion-modal .ion-page:not(ion-nav .ion-page) {
  position: relative;

  contain: layout style;

  height: 100%;
}
```

to become:

```css
ion-modal .ion-page:not(ion-nav.ion-page) {
  position: relative;

  contain: layout style;

  height: 100%;
}
```

### Expected Behavior

Whitespace should be preserved during the minification of the CSS bundle. 

### Steps to Reproduce

1. Visit the minified CSS bundle: https://cdn.jsdelivr.net/npm/@ionic/core/css/ionic.bundle.css
2. Search for the invalid output: `ion-modal .ion-page:not(ion-nav.ion-page)`
3. Observe: Selector is missing a space between `ion-nav` and `.ion-page` (as seen in the source code)

### Code Reproduction URL

N/A

### Ionic Info

N/A
