### ISSUE TITLE
bug: logical property support detection is incorrect

### ISSUE THREAD

**Issue by darrylnoakes** [ionic-team/ionic-framework#25902]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Currently, on `ion-toggle` and other components, a media query is used to check if `margin-inline-start` (or a prefixed version) is supported, and then `padding-left` and `padding-right` are set to `unset` and `padding-inline` is set instead.
The full properties have actually been supported to some extent in most major browsers for over 10 years.
_However_, the shorthands (`margin-inline` and such) are only supported in much later versions of browsers than the full property (`margin-inline-start` and such). This means that the case will often be that no padding/margin is actually applied.

### Expected Behavior

The media queries that check for support should check for support for the actual properties used.

### Steps to Reproduce

No definite steps, although you could try inspecting `ion-toggle` in Chrome before version 87 or Safari before version 14.1.

### Ionic Info

```
Ionic:

   Ionic CLI       : 6.16.3 (C:\Users\Darryl\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/vue 6.2.6

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.4.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.12.1
   OS     : Windows 10
```

### Additional Information

Relevant: https://caniuse.com/css-logical-props

**Comment by liamdebeasi** [comment]
Thanks for the report. Are you able to provide a screenshot of the styles not being applied on an older browser/device? We use a SASS mixin to generate the `margin/padding-inline` values, but we use the long form values: https://github.com/ionic-team/ionic-framework/blob/7315e0157b917d2e3586c64f8082026827812943/core/src/themes/ionic.mixins.scss#L260-L263

I tried to reproduce this on my end: https://codepen.io/liamdebeasi/pen/poVyeeV
Inspecting in Chrome does show `padding-inline: 2px 18px` on `ion-toggle`, but the actual generated code from Ionic is the following:

```css
@supports ((-webkit-margin-start: 0) or (margin-inline-start: 0)) or (-webkit-margin-start: 0) {
      :host(.in-item[slot=start]) {
      padding-left: unset;
      padding-right: unset;
      -webkit-padding-start: 2px;
      padding-inline-start: 2px;
      -webkit-padding-end: 18px;
      padding-inline-end: 18px;
  }
}
```

It may be that Chrome is trying to simplify the CSS values in the inspector (or maybe it is doing this simplification when it should not be?).
