### ISSUE TITLE
bug: modal text color is set incorrectly when app and system dark mode settings aren't the same

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/ionic-framework#26060]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Hi!,

The CCS has strange behavior when you play with the dark and light theme of ionic and the operating system.

**dark ionic, dark windows OK**
![dark-ionic-dark-windows-ok](https://user-images.githubusercontent.com/18282247/193404686-6d5d9a78-f7b9-43b4-bf29-b090200de4a3.jpg)

**dark ionic, light windows KO**
![dark-ionic-light-windows-ko1](https://user-images.githubusercontent.com/18282247/193404701-aab504dc-c198-4aa2-a476-7947b7d64d97.jpg)
![dark-ionic-light-windows-ko2](https://user-images.githubusercontent.com/18282247/193404703-70667e67-6aa8-4c32-8b03-5ed7f6a2f58c.jpg)

**light ionic, light windows OK**
![light-ionic-light-windows-ok](https://user-images.githubusercontent.com/18282247/193404741-9a0753e2-e2d8-45db-b351-5c96096460f9.jpg)

**light ionic, dark windows KO**
![light-ionic-dark-windows-ko1](https://user-images.githubusercontent.com/18282247/193404717-924ed08f-2df1-4df7-aa10-f7f067dded45.jpg)
![light-ionic-dark-windows-ko2](https://user-images.githubusercontent.com/18282247/193404775-546af5d4-e8a8-430d-a1a9-f5f957b1e412.jpg)

### Expected Behavior

It is expected that the elements be seen, and also pass the contrast color and have a good visibility.

### Steps to Reproduce

Create a new project, follow the dark theme guide: https://ionicframework.com/docs/theming/dark-mode#ionic-dark-theme. Remove the media query to use only the body.dark and change the theme both in ionic and in the operating system.

### Code Reproduction URL

https://github.com/Marius-Romanus/ionic-bug-css

### Ionic Info

@ionic/angular 6.2.9

**Comment by Marius-Romanus** [comment]
Hello @liamdebeasi, I just wanted to know if you are looking at this, or if I make a solution in my project. Thank you!

**Comment by liamdebeasi** [comment]
Hey there, apologies for the delay. Yes we will look at this soon.

**Comment by amandaejohnston** [comment]
Hello! I'm still trying to isolate the cause of this, but I wanted to give a quick update. The issue seems to be specific to `ion-modal`, and also shows with components other than `ion-datetime`. (For example, a random `ion-text` placed underneath the datetime also exhibits the incorrect text color.)

As a workaround, you could use `ion-popover` instead of `ion-modal`; I haven't been able to replicate the issue that way.

**Comment by amandaejohnston** [comment]
It looks like the issue here comes down to `ion-modal` overwriting the text color with `--ion-color-primary-contrast` when it shouldn't, or not overwriting it with `--ion-text-color` when it should. Normal modals don't show this problem because including an `ion-content` inside the modal sets the text color to what it should be, but including an `ion-content` isn't the intended usage with `ion-datetime-button`.

There are a few possible workarounds here:
1. Manually set the `color` CSS property on either the `ion-modal` or the `ion-datetime`, updating the value depending on whether dark mode is toggled or not.
2. Keep the app's dark mode setting in sync with the device's by leveraging the `prefers-color-scheme` media query from the default `variables.scss`, rather than commenting that block out.
3. Use `ion-popover` instead of `ion-modal`, as mentioned previously.

**Comment by riderx** [comment]
I had the same problem, **the shadow dom was killing my vibe**.
Because ionic elements are not always present, so even patch them in JS is not easy.

I found a beautiful and horrible solution in same time:
# Todo 
add this in your global css to detect components addition in the dom
```css
@keyframes nodeInserted {
  from {
      outline-color: #fff;
  }
  to {
      outline-color: #000;
  }
}

@-moz-keyframes nodeInserted {
  from {
      outline-color: #fff;
  }
  to {
      outline-color: #000;
  }
}

@-webkit-keyframes nodeInserted {
  from {
      outline-color: #fff;
  }
  to {
      outline-color: #000;
  }
}

@-ms-keyframes nodeInserted {
  from {
      outline-color: #fff;
  }
  to {
      outline-color: #000;
  }
}

@-o-keyframes nodeInserted {
  from {
      outline-color: #fff;
  }
  to {
      outline-color: #000;
  }
}

.detect-control {
  animation-duration: 0.01s;
  -o-animation-duration: 0.01s;
  -ms-animation-duration: 0.01s;
  -moz-animation-duration: 0.01s;
  -webkit-animation-duration: 0.01s;
  animation-name: nodeInserted;
  -o-animation-name: nodeInserted;
  -ms-animation-name: nodeInserted;
  -moz-animation-name: nodeInserted;
  -webkit-animation-name: nodeInserted;
}
```
Then add to your datetime the class `detect-control`
```html
    <ion-item class="ion-justify-content-between form-row">
      <ion-label position="fixed">Date de début</ion-label>
      <ion-datetime-button slot="end" datetime="ACH_DATE_DEBUT"></ion-datetime-button>
      <ion-popover [keepContentsMounted]="true">
        <ng-template>
          <ion-datetime class="some-control"
          id="ACH_DATE_DEBUT" formControlName="ACH_DATE_DEBUT"></ion-datetime>
        </ng-template>
      </ion-popover>
    </ion-item>
```
Now add where you need the detection and the patch:
```typescript
  ionViewDidEnter() {
    document.addEventListener('animationstart', (event) => {
        const myElement = event.target as HTMLElement;
        if (event.animationName === 'nodeInserted' && myElement.tagName === 'ION-DATETIME') {
        const sheet = new CSSStyleSheet();
        sheet.replaceSync(`:host .calendar-day.calendar-day-active::after { background: none; }`);
        const elemStyleSheets                   = myElement.shadowRoot.adoptedStyleSheets;
        myElement.shadowRoot.adoptedStyleSheets = [...elemStyleSheets, sheet];
      }
    }, false);
  }
```
My issue was the day-active::after was white and my text was white also, no clue why, impossible to use a part for that.
It's inspired by http://www.backalleycoder.com/2012/04/25/i-want-a-damnodeinserted/

Took me 2 hours, I hate shadow dom as much as I like it.
