### ISSUE TITLE
improvement: Spinner MD rotate

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-framework#26906]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [X] v7.x
- [ ] Nightly

### Current Behavior

I would rotate the spinner like in [Material Design specs](https://m2.material.io/components/progress-indicators#usage). Just like the type `crescent`.

| Ionic | MD |
| --- | --- |
| ![ionic](https://user-images.githubusercontent.com/60390085/222744594-e625e6ec-0e26-42da-9b11-cadd6170eb7c.gif) | ![md](https://user-images.githubusercontent.com/60390085/222744595-36ca9eb2-9a71-4b3f-b7ce-0db303803337.gif)|
|Circle start/stop on 3 o'clock. | Circle itself rotates to appear more natural. |

### Expected Behavior

bla

### Steps to Reproduce

bla

### Ionic Info

bla

**Comment by amandaejohnston** [comment]
Thank you for the request. I agree that it would be good to match the MD spec better here. MD 3 also has a [slightly different animation](https://m3.material.io/components/progress-indicators/specs#ee9371db-a697-4f97-ae59-bf246354bb43), so we'll need to sort out which we'll be copying depending on where we land with MD 3 support.

**Comment by danielkleebinder** [comment]
@brandyscarney The second birthday of this issue is not far along. Any news?

@infacto @averyjohnston You can add the following code snippet to your global styles as a temporary workaround. It has been extracted from the [Material Web Dev Docs](https://material-web.dev/components/progress/):
```css
@keyframes md-spinner-rotate {
  100% {
    transform: rotate(360deg);
  }
}

ion-spinner {
  animation-name: md-spinner-rotate;
  animation-iteration-count: infinite;
  animation-timing-function: linear;
}

```
