### ISSUE TITLE
bug(input & select): inconsistent label placement

### ISSUE THREAD

**Issue by EinfachHans** [ionic-team/ionic-framework#27194]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

The floating label placement of an outlined `<ion-select>` seems buggy in my applications so i debugged in and mentioned that the current implementation is not very consistent and for example breaks if you set for example a different font size.

Atm the label is placed by (select example):
```css
:host(.select-label-placement-floating) .label-text-wrapper {
    transform: translateY(100%) scale(1);
}
```

what only works if the label (the `label-text-wrapper` element) has1/3 of the height of the select itself as far as i understand. This stops working if you set a different font size on a input/select.

### Expected Behavior

The implementation should force the label to be always centered in the middle. For example:

```css
:host(.select-label-placement-floating) .label-text-wrapper {
    top: 50%;
    transform: translateY(-50%) scale(1);
}
```
and then of course reset the top property on other states

### Steps to Reproduce

Change the font size on a md outlined floating label select or input element

### Ionic Info

Let me know if required
