### ISSUE TITLE
bug: [7.5.0] Assumes html font size is 16px. Html `font-size: 10px` makes the text small for all ionic components.

### ISSUE THREAD

**Issue by fieldscage** [ionic-team/ionic-framework#28361]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

For the past 3 years of using Ionic, we have always used rem for font sizes and styling dimensions. However, we set the html font size to 10px and the body font size to 1.6rem. This allows us to write `margin: 1rem` for a 10px margin. 

After upgrading to 7.5.0, component font sizes are small due to the html font size being 10px. There should be a way to denote to the Ionic framework what the html font size is instead of the framework assuming that the html font size is 16px.

### Expected Behavior

ion-header > ion-toolbar > ion-title font size is 12.5px
Expected: 20px

ion-button font-size is 8.75px
Expected: 14px

### Steps to Reproduce

1. ionic start myApp blank
2. Choose Vue
3. Add code to App.vue
```
<style lang="css">
html {
    font-size: 10px;
}

body {
    font-size: 1.6rem;
}
</style>
```

### Code Reproduction URL

https://github.com/fieldscage/ionic-component-sizes

### Ionic Info

Ionic:

   Ionic CLI       : 7.1.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 7.5.0

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v18.18.0 (/usr/local/bin/node)
   npm    : 9.8.1
   OS     : macOS 14.0

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this is not a bug in Ionic Framework. While setting `font-size: 10px` on `html` and then doing `font-size: 1.6rem` on `body` works for your use case, that's not a great pattern to implement.

Ionic looks to the root font size to determine how to size the text in its components by using `rem`. In your case, the root font size is 10px, so all of Ionic's components will be sized based on that. If you don't want the font sizes to be based on 10px, then you shouldn't be setting the root font size to 10px to begin with.

I'd recommend using CSS variables instead of overriding the font sizes for this purpose. Your margins are tightly coupled to the root font size, so this means that any component (not just Ionic components) that uses `rem`  will not render correctly in your app.

Instead, I'd recommend doing the following:

```css
:root {
  --custom-margin-sm: 8px;
  --custom-margin: 10px;
  --custom-margin-md: 14px;
  --custom-margin-lg: 16px;
}
```

These are just example sizes, so you can set them to whatever you want. If you are using SASS, you can use a SASS variable so that the generated CSS variables update as you change the base SASS variable:

```scss
$default-margin: 10px;

:root {
  --custom-margin-sm: $default-margin * 0.8;
  --custom-margin: $default-margin;
  --custom-margin-md: $default-margin * 1.4;
  --custom-margin-lg: $default-margin * 1.6;
}
```
