### ISSUE TITLE
feat: dynamic font scaling for the Picker component on the iOS platform.

### ISSUE THREAD

**Issue by Kuldeepdev** [ionic-team/ionic-framework#29340]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Ionic Picker component do not respond to font scaling on iOS which can create inaccessible applications particularly for users with low vision for Picker component.  
Ionic apps on Android devices currently support the Android equivalent due to functionality in the Chromium webview.
Developers have also requested a way of adjusting the fonts in their Ionic Picker component consistently.

### Describe the Use Case

In case font size not change in iOS platform for Picker component that can create inaccessible applications particularly for users with low vision. 

### Describe Preferred Solution

Ionic Picker components can use dynamic-font function in scss file. This means devs can change the font size on html and the text in supported Ionic Picker components will scale up/down appropriately

### Related Code

Code Reproduction:
https://github.com/Kuldeepdev/picker-dynamic-font/tree/main

**Comment by thetaPC** [comment]
Thanks for sending in your feature request!

This issue will be closed as we're maintaining alignment with iOS's picker structure, which doesn't include font scaling. However, you can still customize elements within `ion-picker` to scale along with fonts in your app.

```css
.picker-col .picker-opt,
.picker-col .picker-prefix,
.picker-col .picker-suffix {
  font-size: 1.375rem;
}

.picker-toolbar .picker-button
 .picker-toolbar .picker-button.ion-activated {
  font-size: 0.875rem;
}
```
