### ISSUE TITLE
bug: Backdrop only visible for first modal

### ISSUE THREAD

**Issue by fudom** [ionic-team/ionic-framework#29815]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

It seems that the backdrop of e.g. modal is only visible for the first modal. This makes neasted modals look confusing. It's not about fullscreen modals.

### Expected Behavior

In ealier versions the backdrops were visible for each modal. I guess this has been changed, because multiple modals with each have it's own backdrop visible, leads to darker and darker background (up to black).

But I would rather show the last backdrop and not the first one. Otherwise, the nested modals are on top of each other and it is difficult to see what the topmost modal is.

My current workaround is:

```scss
ion-modal.modal-default.show-modal:last-of-type {
  // I set --ion-backdrop-opacity in variables theme dependent.
  --backdrop-opacity: var(--ion-backdrop-opacity, 0.33) !important;
}
```

### Steps to Reproduce

1. Create modals; not fullscreen; different sizes.
2. In a modal, open another.
3. See that the backdrop is only visible on the first modal. Not on the second one. 

### Code Reproduction URL

https://codepen.io/fudom/pen/zYVLXxO

### Ionic Info

No Ionic repo (no ionic info available). But it does not matter in this case. I use Angular with Ionic 8.2.x. But see CodePen too.

### Additional Information

With my workaround and proposal, you see this effect.

| Before | After |
| --- | --- |
|![before](https://github.com/user-attachments/assets/3d2ad892-5038-41c3-a6ea-7cf81758e283)|![after](https://github.com/user-attachments/assets/100058e5-3815-4fd5-a7c9-bae13642889b)|

@liamdebeasi cc

**Comment by liamdebeasi** [comment]
There might be a way to make this behavior a prop or something that devs can toggle. You could check with the team and see if this is a feature they'd be willing to consider.

**Comment by alexsantoshb** [comment]
I have that same issue yet.

**Comment by thetaPC** [comment]
Thanks for the report, and sorry it sat for so long.

Verified on the latest v9, in both `md` and `ios` modes.

You're right, and the earlier "this is intentional" answer doesn't hold up. Here's what happens: when you open a modal from inside another modal, only the bottom modal gets a dimmed background and a drop shadow. Every modal stacked above it is drawn flat, so the modal you just opened looks like a panel glued onto the one beneath it rather than a dialog on top of it. Ionic does this on purpose to stop the background getting darker with every modal, but it keeps the dimming on the bottom modal, which is the one position where it separates nothing.

We checked this against the designs Ionic targets. Material Design keeps a scrim on every open dialog, and native iOS dims the sheet directly beneath the topmost one. Ionic's own card modals do the same thing, dimming the view behind them as they open. Default modals are the odd one out, so this is a bug on our end rather than a design choice, and your instinct to move the backdrop to the last modal is the right one.

Until it's fixed, this gets you the corrected behaviour on 8.x and 9.x, in a global stylesheet:

```css
/* Any open modal with another open modal above it loses its backdrop and shadow. */
ion-modal.modal-default.show-modal:has(~ ion-modal.modal-default.show-modal) {
  --backdrop-opacity: 0;
  --box-shadow: none;
}

/* The topmost open modal keeps them. */
ion-modal.modal-default.show-modal:not(:has(~ ion-modal.modal-default.show-modal)) {
  --backdrop-opacity: var(--ion-backdrop-opacity, 0.32);
  --box-shadow: 0 28px 48px rgba(0, 0, 0, 0.4);
}
```

This is close to your `:last-of-type` version but keyed on `.show-modal` instead, so a dismissed modal still sitting in the DOM can't be mistaken for the topmost one. It needs no `!important`, and it holds the background at a constant opacity no matter how deep the stack goes, so you don't get the progressive darkening the current rule was written to avoid.

Tracked for a fix in `@ionic/core`.
