### ISSUE TITLE
feat: toast - allow fine grained control over toast position

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-framework#29990]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

The toast either gets in the way, or is out of eyesight.

I want to position it as a lower-third.

I have an ion-footer / ion-toolbar in my app, and if I put the toast at the bottom then it covers the ui and gets in the way.

Putting it at the middle or top, even I miss it sometimes, as the app developer. Modern phones are tall and its out of my eyesight when I'm pressing an ok or save button in the footer of the screen.

I wanted to adjust it but the component uses css shadow parts and the positioning is done in a part that is not exposed.

This doesn't work because it just moves the text inside the toast, not the background and actual toast:

```css
.util-brand-toast::part(container) {
  transform: translate3d(0, -30%, 0) !important;
}
```

This doesn't work because its not exposed:

```css
.util-brand-toast .toast-wraper.toast-bottom {
  transform: translate3d(0, -30%, 0) !important;
}
```

This does "work" but it affects the outer container, and I'm nervous that it's not a clean way of doing things:

```css
.util-brand-toast {
  transform: translate3d(0, -30%, 0) !important;
}
```

It ends up like this:

<img width="1530" alt="image" src="https://github.com/user-attachments/assets/b1e906b8-dc19-4167-8fab-d50736d96a94">

### Describe the Use Case

Allow fine grained control over the toast position

### Describe Preferred Solution

Access to the `.toast-wrapper` or some setting method.

**Comment by rtpHarry** [comment]
after some more experimentation, ive tentatively gone with:

```css
.util-brand-toast {
  height: 85%;
}
```

Which seems to be work, but I'm nervous about edge cases. 

While researching this, for example, I read an issue with some problems with the Toast, occurring only when the keyboard is displayed. 

I don't yet know how it will react with that, or if there is more that I might be tripped up by.
