### ISSUE TITLE
feat: Make toolbar-container selectable via shadow part

### ISSUE THREAD

**Issue by fudom** [ionic-team/ionic-framework#30068]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

```html
<ion-toolbar>
  #shadow-root (open)
    <div class="toolbar-container" part="container"> <!-- add part -->
```

so we can select it via css

```css
ion-toolbar::part(container) {
  flex-wrap: wrap;
  justify-content: end;
}
```
