### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by Uolsen** [ionic-team/ionic-framework#30146]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [x] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

In Dark mode in Card (ion-card) the items (ion-item) have different background than the card.

![Image](https://github.com/user-attachments/assets/b6fd1053-0c62-4748-b42f-d72ec3cb5240)

### Expected Behavior

It should be the same colour as in "light" mode.

![Image](https://github.com/user-attachments/assets/3bf3be3c-9f50-4a50-9bd4-1180c1fb19de)

### Steps to Reproduce

I forked default "Card with Items" code from official documentation and only changed theme to "dark.always.css".

https://ionicframework.com/docs/api/card#list-card

### Code Reproduction URL

https://stackblitz.com/edit/hp73tq62?file=src%2FApp.vue

### Ionic Info

Ionic:

   Ionic CLI       : 7.2.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 8.4.1

Capacitor:

   Capacitor CLI      : 6.1.2
   @capacitor/android : not installed
   @capacitor/core    : 6.1.2
   @capacitor/ios     : 6.1.2

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v21.7.3
   npm    : 10.5.0
   OS     : macOS Unknown

**Comment by Uolsen** [comment]
If someone will have the same issue the quick fix could be:
```
<ion-list class="bg-transparent">
    <ion-item style="--background: transparent">
```

PS: I'm using Tailwind CSS. With basic CSS just use `<ion-list style="background: transparent">`

**Comment by Youka** [comment]
Bug still existent.

Alternative solution is setting the parent container background as `ion-item` background:
```html
<ion-card>
  <ion-card-content>
    <ion-list>
      <ion-item>...</ion-item>
    </ion-list>
  </ion-card-content>
</ion-card>
```
```css
ion-item {
  --background: var(--ion-card-background);
}
```

**Comment by howlettga** [comment]
This is till happening. Can someone take a look at this? I am not using a card but I do have a list within a modal. It seems like lists within a content overlay are broken in dark mode, and it's annoying to have to repeat this simple fix everywhere i use a list in my app essentially.

by the way I have to make the list background and background-color transparent, as well as the item

**Comment by howlettga** [comment]
here is the global `styles.scss` fix i am working on. I am afraid there will be unintended consequences because I am not testing that heavy
```scss
ion-modal, ion-card {
  ion-list {
    --background: transparent !important;
    background-color: transparent !important;

    ion-item {
      --background: transparent !important;
    }
  }
  ion-accordion {
    ion-item[slot="content"] {
      --background: transparent !important;
    }
  }
}
```

**Comment by howlettga** [comment]
I've also noticed that `ion-chip` elements have a ubiquitous black background unlike light mode. here is some style override for that:

```scss
@media (prefers-color-scheme: dark) {
	ion-chip.ion-color-primary {
		background: #1a1f2e;
	}

	ion-chip.ion-color-secondary {
		background: #1a1f2b;
	}

	ion-chip.ion-color-tertiary {
		background: #1e1d2a;
	}

	ion-chip.ion-color-success {
		background: #1a221e;
	}

	ion-chip.ion-color-warning {
		background: #252118;
	}

	ion-chip.ion-color-danger {
		background: #251a1c;
	}

	ion-chip.ion-color-orange {
		background: #25201a;
	}

	ion-chip.ion-color-purple {
		background: #231a21;
	}
}
```
